### ISSUE TITLE
The last commit doesnt show up in the yarn package

### ISSUE THREAD

**Issue by varghesethomase** [expo/react-native-responsive-image#8]
I can still see PropTypes being imported from 'react' and when installing via yarn, this package throws an error working with React 16. But checking the code, I found a PR was submitted 3 months ago which got merged. Why is it not available when installing via yarn?

**Comment by mikeduminy** [comment]
@ide please release a new version of this library

**Comment by bsiddiqui** [comment]
@ide tagging you again on this since it's been a while

**Comment by ide** [comment]
Published master as 2.0.0. Also take a look at https://yarnpkg.com/lang/en/docs/selective-version-resolutions/ which lets you publish your own package and use it in lieu of another if you need to make changes to a package on your own timeline.
